public enum Genre{FICTION, NONFICTION, SCIFI, FANTASY, MYSTERY, ROMANCE, THRILLER, HISTORY, HORROR,
    ADVENTURE, GRAPHIC, MANGA, POETRY, COOKBOOK, CHILDREN, GUIDEBOOK, RESEARCH, BIOGRAPHIC, INFORMATIONAL
}

